import { useState } from 'react';
import { ArrowDown, ArrowUpRight, BrainCircuit, Cloud, Code2, Database, Download, Github, Linkedin, Mail, Menu, X, Zap, GraduationCap, BookOpen } from 'lucide-react';
import { projects } from './projects';
import './App.css';

const experience=[
 ['Wells Fargo','Senior Software Engineer (Contract)','Jun 2026 — Present','AI • Micro Frontends',['Architected AI-powered Smart Assist for 4,000+ contact-center agents, reducing customer resolution time by 25%.','Designed Module Federation architecture across 5 micro-frontends supporting 6 lines of business.','Led a 3-developer team across frontend architecture, integrations and production delivery.']],
 ['Goldman Sachs','Senior Software Engineer (Contract)','Jul 2025 — Mar 2026','Performance • FinTech',['Built a cross-border transaction workflow supporting 5,000+ transactions daily.','Reduced page load time by ~10% and interaction latency by ~20% through rendering, caching and state-management optimizations.','Parallelized CI/CD test suites to reduce pipeline execution time by ~33%.']],
 ['Wells Fargo','Senior Software Engineer (Contract)','Jun 2023 — Jun 2025','Contact Center • Distributed Systems',['Built the initial React/TypeScript POC and foundation for a next-generation contact-center platform.','Designed Five9 integration workflows with React, Node.js, REST and AWS.','Established Module Federation and distributed application patterns for independent feature development.']],
 ['Goldman Sachs','Consultant (Contract)','Dec 2021 — Feb 2023','Corporate Lending',['Delivered loan prepayment, credit-rating, origination and loan-management workflows.','Integrated React micro-frontends with distributed Python/Flask services.','Optimized REST APIs, SQL queries, indexing and caching while expanding automated test coverage.']],
 ['Aperia Solutions','IS Lead Developer','Sep 2021 — Dec 2021','Frontend Leadership',['Developed responsive React/TypeScript interfaces for a Fiserv e-commerce platform and led a distributed frontend team.']],
 ['Infosys','Technology Analyst','Feb 2020 — Sep 2021','Data Visualization',['Built React/TypeScript dashboards for Verizon Power, Space & Cooling with REST APIs, Redux, D3.js, Java, Spring Boot and SQL.']],
 ['University of Alabama','Research Assistant','Aug 2018 — Dec 2019','Research • Visualization',['Built academic research web applications including a gamified atomic-configuration visualization platform and data-processing workflows.']],
 ['IBM','Associate Technical Operations','Jul 2015 — Dec 2017','E-commerce',['Developed responsive customer-facing web experiences for Sony e-commerce using JavaScript, jQuery, HTML, CSS, Bootstrap, JSON and AJAX.']]
];
const skills=['React','TypeScript','JavaScript','Node.js','Next.js','Angular','Redux','React Query','React Hook Form','AG Grid','D3.js','Python','Flask','Java','REST APIs','GraphQL','PostgreSQL','MongoDB','AWS','GCP','Azure','Docker','Kubernetes','Module Federation','Jest','Cypress','GitHub Actions','Accessibility'];

function ProjectCard({p,onOpen}){return <button className="project-card" onClick={()=>onOpen(p)}><span className="project-number">{p.number}</span><div><small className="project-company">{p.company} · {p.category}</small><h3>{p.title}</h3><p>{p.summary}</p><div className="project-stack">{p.stack.slice(0,5).map(s=><span key={s}>{s}</span>)}</div></div><ArrowUpRight className="project-arrow"/></button>}
function ProjectModal({p,onClose}){if(!p)return null;return <div className="modal-backdrop" onClick={onClose}><article className="modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose}><X/></button><span className="kicker">PROJECT {p.number} / CASE STUDY</span><h2>{p.title}</h2><p className="modal-summary">{p.summary}</p><div className="case-copy"><div><label>CHALLENGE</label><p>{p.challenge}</p></div><div><label>APPROACH</label><p>{p.solution}</p></div></div><div className="modal-grid"><div><label>IMPACT</label>{p.impact.map(x=><strong key={x}>{x}</strong>)}</div><div><label>STACK</label><div className="modal-tags">{p.stack.map(x=><span key={x}>{x}</span>)}</div></div></div><div className="modal-architecture"><label>SYSTEM FLOW</label><div className="mini-flow">{p.architecture.map((x,i)=><span key={x}><b>{x}</b>{i<p.architecture.length-1&&<i>→</i>}</span>)}</div></div></article></div>}
export default function App(){const[menu,setMenu]=useState(false);const[selected,setSelected]=useState(null);const go=id=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setMenu(false)};return <div className="app"><header className="nav"><button className="brand" onClick={()=>go('home')}><span>GV</span><small>ENGINEERING</small></button><nav className={menu?'navlinks open':'navlinks'}>{['experience','projects','architecture','skills','research','contact'].map(id=><button key={id} onClick={()=>go(id)}>{id}</button>)}</nav><button className="mobile" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation">{menu?<X/>:<Menu/>}</button></header><main>
<section id="home" className="hero section"><div className="hero-copy"><div className="eyebrow"><span className="pulse"/> SENIOR FULL STACK ENGINEER</div><h1>Gopinath<br/><em>Vasu</em></h1><p className="lead">I architect high-availability web applications and distributed systems across financial services, e-commerce and contact-center platforms — from 0-to-1 products to AI-powered enterprise experiences.</p><div className="hero-actions"><button className="primary" onClick={()=>go('projects')}>Explore my work <ArrowDown size={17}/></button><a className="secondary" href="https://www.linkedin.com/in/gopinathpolasanivasu/" target="_blank" rel="noreferrer">Let's connect <Linkedin size={17}/></a><a className="secondary" href={`${import.meta.env.BASE_URL}Gopinath-Vasu-Resume.pdf`} download="Gopinath-Vasu-Resume.pdf">Download resume <Download size={17}/></a></div><div className="hero-meta"><span>10+ YEARS</span><span>REACT • TYPESCRIPT • NODE</span><span>AWS • AI • ARCHITECTURE</span></div></div><div className="scene" aria-hidden="true"></div><div className="scroll-hint"><ArrowDown size={15}/> scroll to enter</div></section>
<section id="experience" className="section"><div className="section-head"><div><span className="kicker">01 / EXPERIENCE</span><h2>Engineering at scale.</h2></div><p>A career spanning financial services, contact centers, e-commerce, visualization and research.</p></div><div className="timeline">{experience.map((j,i)=><article className="job" key={j[0]+j[2]}><div className="job-index">{String(i+1).padStart(2,'0')}</div><div className="job-main"><div className="job-top"><div><h3>{j[0]}</h3><p>{j[1]}</p></div><span>{j[2]}</span></div><div className="tag">{j[3]}</div><ul>{j[4].map(b=><li key={b}>{b}</li>)}</ul></div></article>)}</div></section>
<section id="projects" className="section projects"><div className="section-head"><div><span className="kicker">02 / SELECTED WORK</span><h2>Projects</h2></div><p>Open a case study to see the challenge, approach, system flow, technology choices and measurable impact.</p></div><div className="project-grid">{projects.map(p=><ProjectCard key={p.id} p={p} onOpen={setSelected}/>)}</div></section>
<section id="architecture" className="section architecture"><div className="section-head"><div><span className="kicker">03 / ARCHITECTURE LAB</span><h2>From interface to system.</h2></div><p>The patterns I use to separate experience, deployment, services, cloud infrastructure and data.</p></div><div className="arch-card"><div className="arch-flow">{[[Code2,'React / TypeScript','Experience layer'],[Zap,'Micro Frontends','Module Federation'],[BrainCircuit,'Node / Python APIs','Services & workflows'],[Cloud,'AWS / Cloud','Infrastructure'],[Database,'SQL / Data','Persistence']].map(([I,t,s],i)=><span className="arch-unit" key={t}><div className={i===0?'arch-node hot':'arch-node'}><I/><strong>{t}</strong><small>{s}</small></div>{i<4&&<div className="connector"/>}</span>)}</div><div className="arch-caption"><span>ARCHITECTURE PRINCIPLE</span><strong>Keep complexity behind clean boundaries.</strong><p>Build independently evolvable experiences, explicit service contracts and reusable components so teams can move quickly without sacrificing reliability.</p></div></div></section>
<section id="skills" className="section"><div className="section-head"><div><span className="kicker">04 / TOOLBOX</span><h2>Technologies I work with.</h2></div><p>Frontend depth with full-stack, cloud, data, testing and delivery experience.</p></div><div className="skill-grid">{skills.map((s,i)=><div className="skill" key={s}><span>{String(i+1).padStart(2,'0')}</span><strong>{s}</strong></div>)}</div></section>
<section id="research" className="section research"><div className="section-head"><div><span className="kicker">05 / RESEARCH & EDUCATION</span><h2>Engineering backed by research.</h2></div></div><div className="research-grid"><article><BookOpen/><span>PUBLICATION · 2020</span><h3>GoCrystal</h3><p>A gamified visual analytics tool for analysis and visualization of atomic configurations and thermodynamic energy models, published in <em>Information Visualization</em>.</p></article><article><GraduationCap/><span>MASTER OF SCIENCE</span><h3>Computer Science</h3><p>The University of Alabama · 2018–2019</p><hr/><span>BACHELOR OF ENGINEERING</span><h3>Computer Science</h3><p>Anna University · 2011–2015</p></article></div></section>
<section id="contact" className="section impact"><div className="impact-copy"><span className="kicker">06 / CONTACT</span><h2>Let's build systems that matter.</h2><p>I bring frontend architecture depth together with backend, cloud and distributed-systems experience, with a focus on measurable product outcomes.</p><div className="contact-links"><a href="mailto:Gopinpv3@gmail.com"><Mail size={17}/> Email me</a><a href="https://www.linkedin.com/in/gopinathpolasanivasu/" target="_blank" rel="noreferrer"><Linkedin size={17}/> LinkedIn</a><a href="https://github.com/gopinathpv" target="_blank" rel="noreferrer"><Github size={17}/> GitHub</a></div></div><div className="metrics"><div><strong>4,000+</strong><span>agents supported</span></div><div><strong>25%</strong><span>resolution-time reduction</span></div><div><strong>5,000+</strong><span>transactions / day</span></div><div><strong>33%</strong><span>faster CI test execution</span></div></div></section>
<footer><div><strong>GV</strong><span>Senior Full Stack Engineer</span></div><div className="social"><a href="https://github.com/gopinathpv" target="_blank" rel="noreferrer"><Github size={18}/></a><a href="https://www.linkedin.com/in/gopinathpolasanivasu/" target="_blank" rel="noreferrer"><Linkedin size={18}/></a><a href="mailto:Gopinpv3@gmail.com"><Mail size={18}/></a></div><small>© 2026 Gopinath Vasu</small></footer></main><ProjectModal p={selected} onClose={()=>setSelected(null)}/></div>}